version:  '3'
services:
  jupyter-scipy-notebook:
    image: jupyter/tensorflow-notebook
    #build:
      #context: .
      #dockerfile: Dockerfile
    volumes:
      - ./:/home/jovyan/work
    ports:
      - 8888:8888